import type { CoursePack } from '../schemas/types';

export const med584: CoursePack = {
  id: 'med584',
  code: 'MED 584',
  title: 'Current Innovations in Educational Technology',
  term: 'Spring 2026',
  description:
    'A structured space to document insights, analyze challenges, pose questions, track growth over time, and connect educational technology innovations to real-world professional practice.',
  sectionLabel: 'Module',

  requirements: {
    publicLinkRequired: true,
    minimumFurtherExplorationAreas: 3,
    requiresFinalSynthesis: true,
    requiresResources: true,
    requiresMedia: false,
  },

  outcomes: [
    { id: 'lo1', label: 'LO1', text: 'Understand the historical and theoretical foundations of educational technology.' },
    { id: 'lo2', label: 'LO2', text: 'Analyze current trends and innovations in educational technology.' },
    { id: 'lo3', label: 'LO3', text: 'Design accessible learning environments for all students using technology.' },
    { id: 'lo4', label: 'LO4', text: 'Explore and evaluate the applications of AI and data analytics in education.' },
    { id: 'lo5', label: 'LO5', text: 'Develop immersive and maker-based learning experiences.' },
    { id: 'lo6', label: 'LO6', text: 'Demonstrate understanding of digital citizenship and media literacy.' },
    { id: 'lo7', label: 'LO7', text: 'Leverage technology to foster collaboration, engagement, and creativity.' },
    { id: 'lo8', label: 'LO8', text: 'Identify and address ethical issues in educational technology use.' },
    { id: 'lo9', label: 'LO9', text: 'Cultivate leadership skills for implementing innovative technologies.' },
    { id: 'lo10', label: 'LO10', text: 'Predict and prepare for future trends in educational technology.' },
    { id: 'lo11', label: 'LO11', text: 'Synthesize course concepts into practical applications through reflections and a capstone project.' },
  ],

  sections: [
    {
      id: 'module-1',
      number: 1,
      title: 'Foundations of Educational Technology & Innovation',
      description: 'Explore the history, evolution, and theoretical foundations of educational technology.',
      keyFrameworks: ['Behaviorism', 'Cognitivism', 'Constructivism', 'Connectivism', 'Cognitive Load Theory', 'SAMR', 'TPACK'],
      topics: [
        { id: 'm1-history', title: 'History & Evolution of Edtech', required: true },
        { id: 'm1-what-is-edtech', title: 'What is Edtech & Learning Theories', required: true },
        { id: 'm1-samr-tpack', title: 'SAMR/TPACK', required: true },
        { id: 'm1-infrastructure', title: 'Infrastructure, Instructional Technology, and Environment', required: false },
      ],
    },
    {
      id: 'module-2',
      number: 2,
      title: 'Designing Accessible Learning Environments for All Learners',
      description: 'Learn to design inclusive learning experiences using UDL, ISTE standards, and culturally responsive teaching.',
      keyFrameworks: ['UDL', 'NETP', 'ISTE', 'Culturally Responsive Teaching', 'Digital Equity'],
      topics: [
        { id: 'm2-udl', title: 'UDL', required: true },
        { id: 'm2-netp', title: 'NETP: Digital Use, Digital Design, and Digital Access Divides', required: true },
        { id: 'm2-iste', title: 'ISTE Standards', required: true },
        { id: 'm2-crt', title: 'Culturally Responsive Teaching', required: false },
        { id: 'm2-digital-divide', title: 'Digital Divide and Access', required: false },
      ],
    },
    {
      id: 'module-3',
      number: 3,
      title: 'Artificial Intelligence in Education',
      description: 'Explore AI applications, ethical considerations, and data analytics in educational settings.',
      keyFrameworks: ['AI Ethics', 'Data Privacy', 'Algorithmic Bias', 'Personalized Learning', 'Adaptive Learning'],
      topics: [
        { id: 'm3-ai-ethics', title: 'AI Ethical Considerations', required: true },
        { id: 'm3-ai-benefits', title: 'Benefits of AI in Education', required: true },
        { id: 'm3-personalized', title: 'Personalized and Adaptive Learning', required: true },
        { id: 'm3-data-analytics', title: 'Data Analytics in Education', required: false },
        { id: 'm3-ai-literacy', title: 'AI Literacy and Critical Evaluation', required: false },
      ],
    },
    {
      id: 'module-4',
      number: 4,
      title: 'Immersive Technologies and the Maker Movement',
      description: 'Discover AR/VR, XR, maker learning, and computational thinking for education.',
      keyFrameworks: ['XR', 'AR', 'VR', 'Maker Learning', 'Computational Thinking', 'Experiential Learning'],
      topics: [
        { id: 'm4-arvr', title: 'AR/VR Immersive Learning Experiences', required: true },
        { id: 'm4-xr', title: 'XR for Teaching and Learning', required: true },
        { id: 'm4-maker', title: 'Maker Movement', required: true },
        { id: 'm4-computational', title: 'Computational Thinking', required: false },
        { id: 'm4-designing', title: 'Designing Immersive Learning Experiences', required: false },
      ],
    },
    {
      id: 'module-5',
      number: 5,
      title: 'Digital Citizenship & Media Literacy',
      description: 'Develop understanding of digital citizenship, media literacy, and online safety.',
      keyFrameworks: ['Digital Citizenship', 'Media Literacy', 'ISTE', 'Online Safety', 'Digital Ethics'],
      topics: [
        { id: 'm5-citizenship', title: 'Digital Citizenship & Media Literacy', required: true },
        { id: 'm5-iste-integration', title: 'Integrating Digital Citizenship through ISTE Standards', required: true },
        { id: 'm5-role-modeling', title: 'Positive Digital Role Modeling', required: false },
        { id: 'm5-curriculum', title: 'Digital Citizenship Curriculum', required: false },
        { id: 'm5-privacy', title: 'Privacy, Cyberbullying, and Online Responsibility', required: false },
      ],
    },
    {
      id: 'module-6',
      number: 6,
      title: 'Learning is Social: Social Media & Gamification',
      description: 'Explore professional learning communities, social media for learning, and gamification strategies.',
      keyFrameworks: ['Professional Learning Communities', 'Social Learning', 'Gamification', 'Game-Based Learning', 'Motivation', 'Collaboration'],
      topics: [
        { id: 'm6-plc', title: 'Becoming a Connected Educator: The Power of PLCs', required: true },
        { id: 'm6-social-media', title: 'Social Media for Professional Learning', required: true },
        { id: 'm6-gamification', title: 'The Power of Gamification in the Classroom', required: true },
        { id: 'm6-gbl', title: 'Gamification vs. Game-Based Learning', required: false },
        { id: 'm6-gamified-experience', title: 'Gamified Learning Experience', required: false },
      ],
    },
    {
      id: 'module-7',
      number: 7,
      title: 'Student-Centered Learning',
      description: 'Understand the shift toward student-centered learning, learner agency, and personalized approaches.',
      keyFrameworks: ['Student-Centered Learning', 'Learner Agency', 'Blended Learning', 'Individualized Learning', 'Personalized Learning'],
      topics: [
        { id: 'm7-shift', title: 'The Shift Toward Student-Centered Learning and the Role of Edtech', required: true },
        { id: 'm7-action', title: 'Student-Centered Learning in Action', required: true },
        { id: 'm7-blended', title: 'Blended to Individualized Learning', required: false },
        { id: 'm7-agency', title: 'Learner Agency', required: false },
      ],
    },
    {
      id: 'module-8',
      number: 8,
      title: 'Future Trends and Capstone Project',
      description: 'Predict future trends, complete final synthesis, and develop capstone micro-innovation.',
      keyFrameworks: ['Future Trends', 'Data-Driven Decision Making', 'Strategic Leadership', 'Micro-Innovation', 'Reflective Synthesis'],
      topics: [
        { id: 'm8-future', title: 'Predicting the Future of Educational Technology: A Data-Driven Approach', required: true },
        { id: 'm8-emerging', title: 'Emerging Technologies', required: true },
        { id: 'm8-trends', title: 'Future Trends in Edtech', required: false },
        { id: 'm8-synthesis', title: 'Final Reflection Journal Synthesis', required: true },
        { id: 'm8-capstone', title: 'Edtech Micro-Innovation Capstone', required: true },
      ],
    },
  ],

  reflectionLenses: [
    { id: 'course-connection', label: 'Course Connection', description: 'How does this connect to course outcomes?', promptHint: 'Which learning outcomes does this relate to?' },
    { id: 'professional-practice', label: 'Professional Practice', description: 'How will I apply this in my work?', promptHint: 'What specific changes will I make in my practice?' },
    { id: 'ethical-equity', label: 'Ethical/Equity Considerations', description: 'What ethical or equity issues arise?', promptHint: 'Who might be impacted? What biases exist?' },
    { id: 'accessibility', label: 'Accessibility', description: 'How does this support all learners?', promptHint: 'How does this align with UDL principles?' },
    { id: 'samr-tpack', label: 'SAMR/TPACK', description: 'Where does this fit in SAMR/TPACK?', promptHint: 'Is this substitution, augmentation, modification, or redefinition?' },
    { id: 'udl', label: 'UDL', description: 'How does this support UDL?', promptHint: 'Multiple means of engagement, representation, action/expression?' },
    { id: 'ai-data-privacy', label: 'AI/Data Privacy', description: 'What AI or data privacy concerns exist?', promptHint: 'How is student data protected? What AI biases exist?' },
    { id: 'digital-citizenship', label: 'Digital Citizenship', description: 'How does this relate to digital citizenship?', promptHint: 'What digital literacy skills are needed?' },
    { id: 'student-centered', label: 'Student-Centered Learning', description: 'How does this empower learners?', promptHint: 'How does this increase learner agency?' },
    { id: 'future-trends', label: 'Future Trends', description: 'How might this evolve?', promptHint: 'What emerging technologies could impact this?' },
    { id: 'capstone-possibility', label: 'Capstone Possibility', description: 'Could this become a capstone project?', promptHint: 'Is there a micro-innovation opportunity here?' },
  ],

  rubrics: [
    {
      id: 'journal-setup',
      title: 'Reflection Journal Setup (Week 1)',
      totalPoints: 20,
      checks: [
        {
          id: 'organization-structure',
          label: 'Organization and Structure',
          description: 'Journal is well-organized, with clear sections for each module. Easy to navigate.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Journal is well-organized, with clear sections for each module. Easy to navigate.', points: 5 },
            { rating: 'Good', description: 'Journal is organized, with sections for each module. Mostly easy to navigate.', points: 4 },
            { rating: 'Satisfactory', description: 'Journal has sections for each module but may be somewhat disorganized.', points: 3 },
            { rating: 'Needs Improvement', description: 'Journal lacks clear organization. Difficult to navigate.', points: 2 },
            { rating: 'Incomplete', description: 'Journal is not organized or structured.', points: 0 },
          ],
        },
        {
          id: 'content-module-1',
          label: 'Content for Module 1',
          description: 'Comprehensive notes, reflections, and questions for Module 1.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Comprehensive notes, reflections, and questions for Module 1. Thoroughly outlines Module 1 materials.', points: 5 },
            { rating: 'Good', description: 'Good notes, reflections, and questions set up for Module 1.', points: 4 },
            { rating: 'Satisfactory', description: 'Basic notes and reflections set up for Module 1.', points: 3 },
            { rating: 'Needs Improvement', description: 'Minimal notes and reflections set up for Module 1.', points: 2 },
            { rating: 'Incomplete', description: 'No content set up for Module 1.', points: 0 },
          ],
        },
        {
          id: 'use-of-media',
          label: 'Use of Media',
          description: 'Effectively uses chosen media to enhance the journal.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Effectively uses chosen media to enhance the journal. Media is well-integrated and adds value.', points: 5 },
            { rating: 'Good', description: 'Uses chosen media effectively. Media is integrated and adds some value.', points: 4 },
            { rating: 'Satisfactory', description: 'Basic use of chosen media. Media is present but not well-integrated.', points: 3 },
            { rating: 'Needs Improvement', description: 'Minimal use of chosen media. Media does not add value.', points: 2 },
            { rating: 'Incomplete', description: 'No use of media or media is not linkable.', points: 0 },
          ],
        },
        {
          id: 'technical-quality',
          label: 'Technical Quality',
          description: 'Journal is free of technical errors. All links work correctly.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Journal is free of technical errors. All links work correctly.', points: 5 },
            { rating: 'Good', description: 'Journal has minor technical errors. Most links work correctly.', points: 4 },
            { rating: 'Satisfactory', description: 'Journal has some technical errors. Some links may not work correctly.', points: 3 },
            { rating: 'Needs Improvement', description: 'Journal has significant technical errors. Many links do not work correctly.', points: 2 },
            { rating: 'Incomplete', description: 'Journal is not functional due to technical errors.', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'final-journal',
      title: 'Final Reflection Journal Submission',
      totalPoints: 25,
      checks: [
        {
          id: 'comprehensive-coverage',
          label: 'Comprehensive Coverage of All Modules',
          description: 'Thorough notes from all 8 modules, covering key concepts, discussions, and readings.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Thorough notes from all 8 modules, covering key concepts, discussions, and readings with clear connections.', points: 5 },
            { rating: 'Proficient', description: 'Notes from all modules, with key concepts and readings summarized well.', points: 4 },
            { rating: 'Basic', description: 'Notes are included for most modules, but coverage is uneven or limited.', points: 3 },
            { rating: 'Needs Improvement', description: 'Missing notes from multiple modules or coverage is incomplete.', points: 2 },
          ],
        },
        {
          id: 'critical-reflection',
          label: 'Critical Reflection and Personal Insights',
          description: 'Deep reflection on course content, including thoughtful analysis and connections to personal experience.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Deep reflection on course content, including thoughtful analysis and connections to personal experience.', points: 5 },
            { rating: 'Proficient', description: 'Good reflection with relevant insights and some personal connections.', points: 4 },
            { rating: 'Basic', description: 'Basic reflection with limited analysis or personal connections.', points: 3 },
            { rating: 'Needs Improvement', description: 'Minimal reflection, lacking depth or personal insights.', points: 2 },
          ],
        },
        {
          id: 'further-exploration',
          label: 'Identification of Areas for Further Exploration',
          description: 'Clearly identifies multiple areas for further learning, with specific reasons and future learning goals.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Clearly identifies multiple areas for further learning, with specific reasons and future learning goals.', points: 5 },
            { rating: 'Proficient', description: 'Identifies some areas for further exploration, with reasonable explanations.', points: 4 },
            { rating: 'Basic', description: 'Identifies a few areas but with limited detail or unclear reasoning.', points: 3 },
            { rating: 'Needs Improvement', description: 'Few or no areas for further exploration identified.', points: 2 },
          ],
        },
        {
          id: 'organization-coherence',
          label: 'Organization and Coherence of Writing',
          description: 'Well-structured, logically organized, and easy to follow.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Well-structured, logically organized, and easy to follow, with clear transitions between modules.', points: 5 },
            { rating: 'Proficient', description: 'Clear organization with only minor issues in flow or coherence.', points: 4 },
            { rating: 'Basic', description: 'Somewhat organized but lacking clear transitions between sections.', points: 3 },
            { rating: 'Needs Improvement', description: 'Poor organization, making the journal difficult to follow.', points: 2 },
          ],
        },
        {
          id: 'clarity-grammar',
          label: 'Clarity, Grammar, and Presentation',
          description: 'Writing is clear, concise, and free of errors.',
          points: 5,
          levels: [
            { rating: 'Excellent', description: 'Writing is clear, concise, and free of errors, with a polished presentation.', points: 5 },
            { rating: 'Proficient', description: 'Writing is mostly clear, with minimal errors and a clean presentation.', points: 4 },
            { rating: 'Basic', description: 'Writing is understandable but contains several errors.', points: 3 },
            { rating: 'Needs Improvement', description: 'Writing is unclear and contains multiple errors, impacting readability.', points: 2 },
          ],
        },
      ],
    },
  ],

  weeklyPrompts: [
    { id: 'wp1', sectionId: 'module-1', weekNumber: 1, prompt: 'What assumptions about learning have shaped your teaching practice? How might educational technology challenge or reinforce these assumptions?' },
    { id: 'wp2', sectionId: 'module-2', weekNumber: 2, prompt: 'Think of a learner who struggled in your context. How might UDL principles have supported them differently?' },
    { id: 'wp3', sectionId: 'module-3', weekNumber: 3, prompt: 'Where do you see AI already present in your educational context? What concerns or opportunities does this raise?' },
    { id: 'wp4', sectionId: 'module-4', weekNumber: 4, prompt: 'Describe a learning experience that could be transformed through immersive technology. What would change?' },
    { id: 'wp5', sectionId: 'module-5', weekNumber: 5, prompt: 'What digital citizenship challenges have you observed? How might you address them proactively?' },
    { id: 'wp6', sectionId: 'module-6', weekNumber: 6, prompt: 'How has your professional learning network evolved? What role does social media play?' },
    { id: 'wp7', sectionId: 'module-7', weekNumber: 7, prompt: 'Where do you see opportunities to increase learner agency in your context?' },
    { id: 'wp8', sectionId: 'module-8', weekNumber: 8, prompt: 'Looking back at your journal, what themes emerge? What micro-innovation could you pursue?' },
  ],
};
